// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZQnu_9MSpeB2A6-HyMkcfLzigx-fUWk',
    appId: '1:20264636038:ios:46d51fb774cea0a9698b07',
    messagingSenderId: '20264636038',
    projectId: 'sepadan-app-2025',
    storageBucket: 'sepadan-app-2025.firebasestorage.app',
    androidClientId: '20264636038-7lu9ada620or1t3tk4b6ekvvuf030cij.apps.googleusercontent.com',
    iosClientId: '20264636038-3fpujgaom8cj4697sjp74f8o0c67f2qd.apps.googleusercontent.com',
    iosBundleId: 'com.sepadan.myapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgqeoH5oO6605Ki5lT5zSSteA5C3KxroA',
    appId: '1:20264636038:android:eb4dbf53073b4c08698b07',
    messagingSenderId: '20264636038',
    projectId: 'sepadan-app-2025',
    storageBucket: 'sepadan-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClEUi2slxxizvYwO9DsyLonClCp7jZk3M',
    appId: '1:20264636038:web:13da525ad060d4dd698b07',
    messagingSenderId: '20264636038',
    projectId: 'sepadan-app-2025',
    authDomain: 'sepadan-app-2025.firebaseapp.com',
    storageBucket: 'sepadan-app-2025.firebasestorage.app',
    measurementId: 'G-TR968T6QTQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZQnu_9MSpeB2A6-HyMkcfLzigx-fUWk',
    appId: '1:20264636038:ios:46d51fb774cea0a9698b07',
    messagingSenderId: '20264636038',
    projectId: 'sepadan-app-2025',
    storageBucket: 'sepadan-app-2025.firebasestorage.app',
    androidClientId: '20264636038-7lu9ada620or1t3tk4b6ekvvuf030cij.apps.googleusercontent.com',
    iosClientId: '20264636038-3fpujgaom8cj4697sjp74f8o0c67f2qd.apps.googleusercontent.com',
    iosBundleId: 'com.sepadan.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClEUi2slxxizvYwO9DsyLonClCp7jZk3M',
    appId: '1:20264636038:web:a9613c0b41265b27698b07',
    messagingSenderId: '20264636038',
    projectId: 'sepadan-app-2025',
    authDomain: 'sepadan-app-2025.firebaseapp.com',
    storageBucket: 'sepadan-app-2025.firebasestorage.app',
    measurementId: 'G-ENQZ91PL80',
  );

}